const hotels = [
  {
    id: 2,
    nombre: "Plaza San Juan",
    email: "plazasanjuan@google.com",
    telefono: "2643432289",
    provincia: "San Juan",
    direccion: "Domingo Faustino Sarmiento 344",
    image: "https://www.hotelplazasanjuan.com/img/galeria/hotelpazasanjuan_5eceb1d2d45de.jpg",
    servicio: ["Desayuno gratis", "Estacionamiento gratis", "Spa"],
  },
  {
    id: 3,
    nombre: "Ker Recoleta Hotel",
    email: "NHCordoba@google.com",
    telefono: "1143487231",
    provincia: "Buenos Aires",
    direccion: "Calle Marcelo T de Alvear 1368",
    image: "https://www.kerhoteles.com.ar/img/_habitaciones/Banner_03.jpg",
    servicio: ["Desayuno gratis", "Minibar", "Estacionamiento gratis", "Spa"],
  },
  {
    id: 4,
    nombre: "Hotel Nuevo Ostende by bund",
    email: "NuevoOstendebund@google.com",
    telefono: "2234950081",
    provincia: "Mar del Plata",
    direccion: "Calle Hipolito Yrigoyen 1737",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/cd/0e/34/hotel-nuevo-ostende.jpg?w=800&h=-1&s=1",
    servicio: ["Wifi", "Estacionamiento gratis", "Spa"],
  },
  {
    id: 5,
    nombre: "",
    email: "NHCordoba@google.com",
    telefono: "1143487231",
    provincia: "Buenos Aires",
    direccion: "Calle Marcelo T de Alvear 1368",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/92/eb/0f/deluxe-studio-ala-moreno--v126700.jpg?w=2400&h=-1&s=1",
    servicio: ["Desayuno gratis", "Minibar", "Estacionamiento gratis", "Spa"],
  },
  {
    id: 6,
    nombre: "",
    email: "NHCordoba@google.com",
    telefono: "1143487231",
    provincia: "Buenos Aires",
    direccion: "Calle Marcelo T de Alvear 1368",
    image: "https://www.kerhoteles.com.ar/img/_habitaciones/Banner_03.jpg",
    servicio: ["Desayuno gratis", "Minibar", "Estacionamiento gratis", "Spa"],
  },
];

export const hotel = {
  id: 1,
  nombre: "NH Córdoba Panorama",
  email: "NHCordoba@google.com",
  telefono: "3515489734",
  provincia: "Córdoba",
  direccion: "Avenida Marcelo T de Alvear 251",
  image: "https://img.nh-hotels.net/W0gk/aN88Z/original/RJSTV_NH_panorama_139.jpg",
  servicio: ["Desayuno gratis", "Internet", "Estacionamiento gratis"],
};

export default hotels;
