export const ALL_HOTELS = "ALL_HOTELS";
export const DETAIL_HOTEL = "DETAIL_HOTEL";
export const DETAIL_CLEAR_HOTEL = "DETAIL_CLEAR_HOTEL";
export const ALL_FAVORITES_HOTELS = "ALL_FAVORITES_HOTELS";
